#!/bin/bash

directory=($(pwd))
cd ~/Hubot
if [ $1 = 'start' ]
then
    export HUBOT_SLACK_TOKEN=$(cat ./scripts/keys/slack/hubot_slack.token)
    ./bin/hubot --adapter slack &
    sleep 10
    ARRAY=($(ps aux | grep hubot | grep slack))
    echo -n "${ARRAY[1]}" > ./operate/hubot.pid
fi
if [ $1 = 'stop' ]
then
    kill $(cat ./operate/hubot.pid)
fi
if [ $1 = 'reboot' ]
then
    operate/launch stop
    operate/launch start
fi
cd ${directory}
