#!/bin/bash

directory=($(pwd))
cd ~/Hubot/scripts/bashes/
xvfb-run wkhtmltoimage https://weather.yahoo.co.jp/weather/jp/13/4410.html picture.png &
sleep 10
if [ $1 = 'today' ]
then
    convert picture.png -crop 310x170+38+375 today.png
elif [ $1 = 'tomorrow' ]
then
    convert picture.png -crop 310x170+358+375 tomorrow.png
elif [ $1 = 'week' ]
then
    convert picture.png -crop 640x225+35+680 week.png
else
    echo 'error'
fi
cd ${directory}
