#!/bin/bash

directory=($(pwd))
cd ~/Hubot/scripts/bashes/
xvfb-run wkhtmltoimage http://weather.livedoor.com/area/forecast/1320800 picture.png &
sleep 10
if [ $1 = 'today' ]
then
    # width x height + PointX + PointY
    convert picture.png -crop 645x250+35+305 today.png
elif [ $1 = 'tomorrow' ]
then
    convert picture.png -crop 645x250+35+590 tomorrow.png
elif [ $1 = 'week' ]
then
    convert picture.png -crop 645x185+35+845 week.png
else
    echo 'error'
fi
cd ${directory}
